version: "3"

services:
  oracledatabase:
    image: container-registry.oracle.com/database/free:23.3.0.0
    ports:
      - "1521:1521"
    env_file: .env
    volumes:
      - oracle_data:/opt/oracle/oradata

volumes:
    oracle_data:
